"""Add uuid instead for image

Revision ID: 593a5e58537b
Revises: cd22f7f73ba2
Create Date: 2025-04-19 21:25:55.519730

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593a5e58537b'
down_revision: Union[str, None] = 'cd22f7f73ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image_id', sa.Uuid(), nullable=False))
    op.drop_constraint('image_image_name_key', 'image', type_='unique')
    op.drop_column('image', 'image_name')
    op.drop_column('image', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('image', sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('image_image_name_key', 'image', ['image_name'])
    op.drop_column('image', 'image_id')
    # ### end Alembic commands ###
