"""Use composite primary key for userfilm

Revision ID: 8d326d544622
Revises: 593a5e58537b
Create Date: 2025-04-24 19:33:17.742836

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d326d544622'
down_revision: Union[str, None] = '593a5e58537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('review', sa.Column('film_id', sa.Uuid(), nullable=False))
    op.drop_constraint('review_user_film_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('review', 'user_film_id')
    op.drop_column('userfilm', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfilm', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('userfilm_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('review', sa.Column('user_film_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_film_id_fkey', 'review', 'userfilm', ['user_film_id'], ['id'], ondelete='CASCADE')
    op.drop_column('review', 'film_id')
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###
