"""Add image name display name film title index

Revision ID: c2c2a1741542
Revises: 9967c12ebcb6
Create Date: 2025-04-18 20:34:30.019244

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c2a1741542'
down_revision: Union[str, None] = '9967c12ebcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_film_title'), 'film', ['title'], unique=False)
    op.add_column('image', sa.Column('image_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'image', ['image_name'])
    op.add_column('user', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    op.drop_constraint(None, 'image', type_='unique')
    op.drop_column('image', 'image_name')
    op.drop_index(op.f('ix_film_title'), table_name='film')
    # ### end Alembic commands ###
