"""Add timestamp attribute

Revision ID: cd22f7f73ba2
Revises: 7268467d2f3c
Create Date: 2025-04-19 14:40:15.504062

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd22f7f73ba2'
down_revision: Union[str, None] = '7268467d2f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('film', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.add_column('image', sa.Column('image_extension', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column('image', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('user', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('user', 'last_updated_at')
    op.alter_column('image', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('image', 'image_extension')
    op.drop_column('film', 'last_updated_at')
    op.drop_column('film', 'created_at')
    # ### end Alembic commands ###
